### ISSUE TITLE
Sistema de referencia para coordenadas

### ISSUE THREAD

**Issue by JMPerez** [IGN-CNIG/API-CNIG#1]
Me gustaría saber cuál es el sistema de referencia para las coordenadas que se le pasan al parámetro `center`.

Por ejemplo, en el código del ejemplo https://github.com/IGN-CNIG/API-CNIG/wiki, `center` recibe el valor `[-467062.8225, 4683459.6216]`. En el wiki no está indicado qué tipo de sistema de referencia se usa.

**Comment by e2molin** [comment]
El sistema de referencia por defecto, [WGS 84 / Pseudo-Mercator -- Spherical Mercator](https://epsg.io/3857). 
Si quisieras configurar el mapa en otro  sistema, por ejemplo [EPSG:4326 WGS84 Lat/Lon](https://epsg.io/4326), escribirías

```
const map = M.map({
  container: 'mapjs',
  center: {
    x: -3.23232333,
    y: 42.2365656,
    draw: true, //Con esto dibujas una marca en el lugar de la coordenada
  },
  controls: ['scale','location'],
  projection: 'EPSG:4326*d',  // Código EPSG del SRS * Unidades (d (degree)/m (meter))
  zoom: 6,
});
```
Más información sobre los parámetros en [este enlace](https://github.com/IGN-CNIG/API-CNIG/wiki/Opciones)

**Comment by JMPerez** [comment]
¡Muchísimas gracias, @e2molin!
