### ISSUE TITLE
TOC y FullTOC y su gestión de capas ráster y vectoriales

### ISSUE THREAD

**Issue by e2molin** [IGN-CNIG/API-CNIG#11]
Por lo que estoy comprobando, el plugin **🔌 FullTOC** no muestra las capas vectoriales, sólo los **WMS** y **WMTS**. Por otro lado, el plugin **🔌 TOC** sí las muestra todas, pero no me permite ni añadir más capas ni jugar con la opacidad. Estoy cargando en mi visualizador una serie de servicios WMS y un fichero geoJSON vectorial. Me gustaría ofrecer al usuario la posibilidad de gestionar las capas ráster y vector:  trabajar con dos TOCs distintos, más el selector de capas base, es un jaleo 👎.

- ¿Está previsto modificar el plugin **🔌 FullTOC** para que admita capas vectoriales?
- Si no es así necesito combinar ambos plugins, pero utilizan el mismo icono en la barra de herramientas y resulta confuso. ¿Sería posible cambiarlo por uno _custom_ o tenéis idea de ofrecerlo ya cambiado?
- Otra opción para salir del aprieto que se me ocurre sería usar el plugin **🔌Vectors** que además permite la digitalización o la carga de ficheros y **WFS**. El problema de este plugin es que no permite gestionar capas cargadas previamente usando por ejemplo el **M.layer.GeoJSON**. ¿Sería posible que reconociera las capas vectoriales previamente cargadas y las añadiera a su listado de capas vectoriales? ¿Hay alguna posibilidad de que al inicializar este plugin esté cargado por defecto una  determinada capa geoJSON? Analizando el código fuente del plugin no lo consigo hacer por APIREST.

Gracias de antemano. Un saludo

**Comment by e2molin** [comment]
Muchas gracias @IngenieroGeomatico 

Estaré atento a los próximos despliegues. Lo he solucionado temporalmente combinando los dos plugins, FullTOC, TOC, y haciendo magia con el CSS **!important**, pero por supuesto se sujeta con pinzas.
![Untitled-1](https://github.com/IGN-CNIG/API-CNIG/assets/1150060/25dd332c-7fd4-4d76-84d1-4e3f2e8e8055)

Un saludo

**Comment by e2molin** [comment]
Hola:
No sé si ya habéis actualizado el plugin **Vectors**. Ya reconoce las capas previamente cargadas en el TOC, lo que pasa es que hay que hacer un truco ✨.  Tienes que pulsar en una de las herramientas, y al actualizar su TOC con la nueva capa, ya aparece la capa vectorial cargada previamente . Es como si en ese punto refrescara un procedimiento en el que comprueba las capas vectoriales cargadas en el mapa.

* Estado del plugin nada más arrancar la App, que tiene una capa vectorial cargada pero que no aparece listada
![image](https://github.com/IGN-CNIG/API-CNIG/assets/1150060/48f043e1-781f-44af-a3a2-f9dd6f2d47cd)

* Aspecto del panel del plugin, si seguidamente hago clic en un botón de crear capa vectorial
![image](https://github.com/IGN-CNIG/API-CNIG/assets/1150060/285404f1-c4bc-4e4b-a002-7b6877dbb88e)

Como ves, Aparece correctamente la nueva capa para editar y sorprendentemente aparece la capa que estaba cargada inicialmente, _Municipios...._

Aprovecho también para recordaros  que el zoom a la capa sigue sin funcionar. Al final del issue #7 os comentaba que tras mirar el código me parece que era por el formato de la capa (geoJSON), que necesita, una llamada en concreto. ¿Podría ser eso?

**Comment by IngenieroGeomatico** [comment]
Buenas @e2molin :

En el próximo despliegue sacamos el selector de capa que unifica y gestiona las capas, puedes verlo aquí: https://componentes-desarrollo.cnig.es/api-core/layerswitcher.jsp?language=es

en principio con ello quedaría resuelto todos los errores reportados
