### ISSUE TITLE
Copiar coordenadas al portapapeles

### ISSUE THREAD

**Issue by e2molin** [IGN-CNIG/API-CNIG#3]
El plugin **[infocoordinates]** permite ir definiendo puntos sobre la cartografía y exportarlos posteriormente en un TXT. En ocasiones a los usuarios les bastaría con poder copiar al portapapeles la información del punto marcado, en geográficas mismamente, sin tener que pasar por el guardado en un fichero. Las etiquetas del plugin tienen una propiedad _noselection_ que impide que las puedas marcar con el cursor del ratón y copiarlas para un Excel u otra aplicación.
Salvo que haya otra opción que no he encontrado, estaría genial añadir un botón extra a la parte inferior (ahora tenéis tres ) que sirviera para copiar al portapapeles la coordenada como texto, separando las coordenadas, por ejemplo, por la coma.

```
# Formato salida en el fichero TXT
Punto:1: 
EPSG:4258: [-3.874589,41.741863,810.045]
EPSG:25830: [427276.34,4621485.81,810.045]

# Formato para el portapapeles
-3.874589,41.741863,810.045,EPSG:4258
```
De esta manera podemos aprovechar la coordenada en otra aplicación, pegándola y _parseándola_. 

Como solución de urgencia, lo que hago actualmente es copiar la URL que me devuelve el plugin **[sharemap]**, pero el problema evidente es que sólo puedo recuperar la coordenada del centro de la pantalla, y es ineficaz cuando buscas una coordenada más exacta.

Gracias de antemano

**Comment by IngenieroGeomatico** [comment]
Buenas @e2molin , Hemos hecho el análisis de la petición aprovechando para mejorar la extensión con más usabilidad. Te mantenemos informado.

**Comment by IngenieroGeomatico** [comment]
Buenas @e2molin ya está en producción tu petición. Puedes comprobarla en: https://www.ign.es/iberpix/

Un saludo y gracias por tu aportación.

**Comment by e2molin** [comment]
Muchas gracias @IngenieroGeomatico , con esta pequeña modificación podemos usar Iberpix para ubicar lugares en la cartografía y traernos de una forma muy sencilla el resultado a nuestro entorno de y trabajo. Además la  función de tipo _Toast_ para enviar notificaciones _flash_ al usuario mejora notablemente la usabilidad sin tener que usar ventanas modales para informar al usuario de sus acciones.
