### ISSUE TITLE
Carga de una capa vectorial definida en Base64

### ISSUE THREAD

**Issue by e2molin** [IGN-CNIG/API-CNIG#7]
Buenos días:

Estoy cargando una capa de mojones, y para ello defino el estilo y las coordenadas en **base64** y lo introduzco embebido en la URL, como [he leído en la wiki](https://github.com/IGN-CNIG/API-CNIG/wiki/5.1.-Parametrizaci%C3%B3n-API-REST)

[Enlace a los mojones](https://www.ign.es/iberpix/?center=-2.62396903221667,43.08529163332584&zoom=15&srs=EPSG:4326&layers=GeoJSON*Mojones*eyJ0eXBlIjoiRmVhdHVyZUNvbGxlY3Rpb24iLCJmZWF0dXJlcyI6W3sidHlwZSI6IkZlYXR1cmUiLCJwcm9wZXJ0aWVzIjp7Im5vbWJyZSI6Ik0xIn0sImdlb21ldHJ5Ijp7ImNvb3JkaW5hdGVzIjpbLTIuNjIzOTY5MDMyMjE2NjcsNDMuMDg1MjkxNjMzMzI1OF0sInR5cGUiOiJQb2ludCJ9fSx7InR5cGUiOiJGZWF0dXJlIiwicHJvcGVydGllcyI6eyJub21icmUiOiJNMiJ9LCJnZW9tZXRyeSI6eyJjb29yZGluYXRlcyI6Wy0yLjYyNTk0Nzg3OTc1MDM0LDQzLjA4NTM1NTI1MTczNjZdLCJ0eXBlIjoiUG9pbnQifX0seyJ0eXBlIjoiRmVhdHVyZSIsInByb3BlcnRpZXMiOnsibm9tYnJlIjoiTTMifSwiZ2VvbWV0cnkiOnsiY29vcmRpbmF0ZXMiOlstMi42Mjg0ODYzMDE4NjMxOCw0My4wODYxMTQ1MDUzNzMxXSwidHlwZSI6IlBvaW50In19LHsidHlwZSI6IkZlYXR1cmUiLCJwcm9wZXJ0aWVzIjp7Im5vbWJyZSI6Ik01In0sImdlb21ldHJ5Ijp7ImNvb3JkaW5hdGVzIjpbLTIuNjMxMzM1MDAwODYxOTEsNDMuMDg2NTkxODMxMzc1M10sInR5cGUiOiJQb2ludCJ9fSx7InR5cGUiOiJGZWF0dXJlIiwicHJvcGVydGllcyI6eyJub21icmUiOiJNNiJ9LCJnZW9tZXRyeSI6eyJjb29yZGluYXRlcyI6Wy0yLjYzMTc3NzczMTg3MjUsNDMuMDg2NzI0MTkzOTAxNl0sInR5cGUiOiJQb2ludCJ9fSx7InR5cGUiOiJGZWF0dXJlIiwicHJvcGVydGllcyI6eyJub21icmUiOiJNNyJ9LCJnZW9tZXRyeSI6eyJjb29yZGluYXRlcyI6Wy0yLjYzMjIxNzczNzU0NjcyLDQzLjA4Njg2MDU5ODIwNjJdLCJ0eXBlIjoiUG9pbnQifX0seyJ0eXBlIjoiRmVhdHVyZSIsInByb3BlcnRpZXMiOnsibm9tYnJlIjoiTTgifSwiZ2VvbWV0cnkiOnsiY29vcmRpbmF0ZXMiOlstMi42MzI2ODY5MTMyNTM0Niw0My4wODcwMDkxNjE0NTc4XSwidHlwZSI6IlBvaW50In19LHsidHlwZSI6IkZlYXR1cmUiLCJwcm9wZXJ0aWVzIjp7Im5vbWJyZSI6Ik05In0sImdlb21ldHJ5Ijp7ImNvb3JkaW5hdGVzIjpbLTIuNjMzNzkyODk3MTYwMjgsNDMuMDg2NDE2ODUwMjYwN10sInR5cGUiOiJQb2ludCJ9fSx7InR5cGUiOiJGZWF0dXJlIiwicHJvcGVydGllcyI6eyJub21icmUiOiJNMTAifSwiZ2VvbWV0cnkiOnsiY29vcmRpbmF0ZXMiOlstMi42MzU3MDg5NDE2Mzk5MSw0My4wODU0NDEzMzk2NjQzXSwidHlwZSI6IlBvaW50In19LHsidHlwZSI6IkZlYXR1cmUiLCJwcm9wZXJ0aWVzIjp7Im5vbWJyZSI6Ik0xMSJ9LCJnZW9tZXRyeSI6eyJjb29yZGluYXRlcyI6Wy0yLjYzODE0Mjk2MTY5Nzk1LDQzLjA4NDE4MzQyMDQzODddLCJ0eXBlIjoiUG9pbnQifX0seyJ0eXBlIjoiRmVhdHVyZSIsInByb3BlcnRpZXMiOnsibm9tYnJlIjoiTTEyIn0sImdlb21ldHJ5Ijp7ImNvb3JkaW5hdGVzIjpbLTIuNjM4OTQyMTAzOTI3NjcsNDMuMDgzNzk0MDUwNzQ3Nl0sInR5cGUiOiJQb2ludCJ9fSx7InR5cGUiOiJGZWF0dXJlIiwicHJvcGVydGllcyI6eyJub21icmUiOiJNMTMifSwiZ2VvbWV0cnkiOnsiY29vcmRpbmF0ZXMiOlstMi42NDA0MjQyNDE5MzUwMiw0My4wODMyNjk0MTE4MDc1XSwidHlwZSI6IlBvaW50In19LHsidHlwZSI6IkZlYXR1cmUiLCJwcm9wZXJ0aWVzIjp7Im5vbWJyZSI6Ik0xNCJ9LCJnZW9tZXRyeSI6eyJjb29yZGluYXRlcyI6Wy0yLjY0MzUwNDA1NDQ2NjE5LDQzLjA4MTk2NTU5MzgyNDNdLCJ0eXBlIjoiUG9pbnQifX0seyJ0eXBlIjoiRmVhdHVyZSIsInByb3BlcnRpZXMiOnsibm9tYnJlIjoiTTE1In0sImdlb21ldHJ5Ijp7ImNvb3JkaW5hdGVzIjpbLTIuNjQ1NTc2NjgzODExNDgsNDMuMDgxMTE3Mjg3NzE2MV0sInR5cGUiOiJQb2ludCJ9fSx7InR5cGUiOiJGZWF0dXJlIiwicHJvcGVydGllcyI6eyJub21icmUiOiJNMTYifSwiZ2VvbWV0cnkiOnsiY29vcmRpbmF0ZXMiOlstMi42NDc4MTk3MTU4NjIwOCw0My4wODAxNzE0OTQ3NjMyXSwidHlwZSI6IlBvaW50In19LHsidHlwZSI6IkZlYXR1cmUiLCJwcm9wZXJ0aWVzIjp7Im5vbWJyZSI6Ik0xNyJ9LCJnZW9tZXRyeSI6eyJjb29yZGluYXRlcyI6Wy0yLjY1MjA2MzY1ODg2NDYyLDQzLjA3ODIyMDg2NTk4NjJdLCJ0eXBlIjoiUG9pbnQifX0seyJ0eXBlIjoiRmVhdHVyZSIsInByb3BlcnRpZXMiOnsibm9tYnJlIjoiTTE4In0sImdlb21ldHJ5Ijp7ImNvb3JkaW5hdGVzIjpbLTIuNjU0NTg3NjI2NTE2NjksNDMuMDc2NjI5OTUyMzYyNF0sInR5cGUiOiJQb2ludCJ9fSx7InR5cGUiOiJGZWF0dXJlIiwicHJvcGVydGllcyI6eyJub21icmUiOiJNMTkifSwiZ2VvbWV0cnkiOnsiY29vcmRpbmF0ZXMiOlstMi42NTY3NzI0NjkzMzI4LDQzLjA3NTcxMTA5MjU4MThdLCJ0eXBlIjoiUG9pbnQifX0seyJ0eXBlIjoiRmVhdHVyZSIsInByb3BlcnRpZXMiOnsibm9tYnJlIjoiTTIwIn0sImdlb21ldHJ5Ijp7ImNvb3JkaW5hdGVzIjpbLTIuNjU5MjAwNTY0NzgwNTgsNDMuMDc0NzMwMDYyMjA4XSwidHlwZSI6IlBvaW50In19LHsidHlwZSI6IkZlYXR1cmUiLCJwcm9wZXJ0aWVzIjp7Im5vbWJyZSI6Ik0yMWEifSwiZ2VvbWV0cnkiOnsiY29vcmRpbmF0ZXMiOlstMi42NjEyMDM2NTA5NzI3LDQzLjA3MzkxMjQyMjA5MjVdLCJ0eXBlIjoiUG9pbnQifX0seyJ0eXBlIjoiRmVhdHVyZSIsInByb3BlcnRpZXMiOnsibm9tYnJlIjoiTTIxIn0sImdlb21ldHJ5Ijp7ImNvb3JkaW5hdGVzIjpbLTIuNjYxMjM5NTUzMjI5NjUsNDMuMDczOTA2MjI1MTE2NV0sInR5cGUiOiJQb2ludCJ9fSx7InR5cGUiOiJGZWF0dXJlIiwicHJvcGVydGllcyI6eyJub21icmUiOiJNMjJhIn0sImdlb21ldHJ5Ijp7ImNvb3JkaW5hdGVzIjpbLTIuNjYxMTgwNTgyODg1MTQsNDMuMDY1NzY0ODI1MjgzM10sInR5cGUiOiJQb2ludCJ9fSx7InR5cGUiOiJGZWF0dXJlIiwicHJvcGVydGllcyI6eyJub21icmUiOiJNMjIifSwiZ2VvbWV0cnkiOnsiY29vcmRpbmF0ZXMiOlstMi42NjExMzIxMDEwMzY1OCw0My4wNjU3NTkwOTgxNzddLCJ0eXBlIjoiUG9pbnQifX1dfQ==*true*eyJwYXJhbWV0ZXJzIjpbeyJmaWxsIjp7ImNvbG9yIjoicmdiYSgyNTUsMCwwLC40KSJ9LCJyYWRpdXMiOjV9XSwiZGVzZXJpYWxpemVkTWV0aG9kIjoiKChzZXJpYWxpemVkUGFyYW1ldGVycyk9Pk0uc3R5bGUuU2ltcGxlLmRlc2VyaWFsaXplKHNlcmlhbGl6ZWRQYXJhbWV0ZXJzLCdNLnN0eWxlLlBvaW50JykpIn0=)

Los pinta correctamente en el color seleccionado, pero cuando despliego las capas vectoriales, y quiero cambiar el estilo, no me deja. Entiendo que si quiero editar geometría, además de permitirme mover un _feature_ de la capa, está habilitada la selección de colores, luego debería dejarme asignar un nuevo color, ¿no?. No me da opción de guardar el estilo que selecciono. 

También he comprobado que cuando pincho en **Zoom a la capa**, no centra en la capa.

Por lo demás, me va estupendo para enviar a un cliente la geometría de los puntos tomados usando el **Iberpix** de base.

Gracias y un saludo

**Comment by IngenieroGeomatico** [comment]
Buenas @e2molin 

El problema radica en la gestión de estilos. Cuando se aplica un estilo a una capa (que es la forma canónica) no se puede editar cuando se intenta cambiar el estilo de un único objeto geográfico (como funciona la extensión vectors).

Dentro del actual contrato tenemos la mejora de la extensión, a si que lo tendremos en cuenta para arreglarlo a nivel usuario.

Muchas gracias por el aporte

**Comment by IngenieroGeomatico** [comment]
Disculpa la tardanza en responder.

El zoom a la capa está solventado. Por otro lado, recomendamos no usar la implementación (aunque a veces no queda de otra para poder realizar desarrollos que no permite la fachada) de la siguiente manera:

`mapjs.setBbox(mapjs.getLayers()[1].getMaxExtent())`

Sobre el estilo, no se ha podido realizar en el contrato actual, pero sigue estando en nuestro radar poder arreglarlo.

Un saludo
