### ISSUE TITLE
Parametrización del BBOX a través de la URL

### ISSUE THREAD

**Issue by e2molin** [IGN-CNIG/API-CNIG#8]
Cuando intento centrar el mapa definiendo el Bounding Box a través de parámetros en la URL según [este enlace de la wiki](https://github.com/IGN-CNIG/API-CNIG/wiki/5.1.-Parametrizaci%C3%B3n-API-REST)

> https://www.ign.es/iberpix/?bbox=-4.724992,43.226957,-4.724674,43.227457&zoom=12&srs=EPSG:4326

no consigo el resultado deseado. Compruebo que variando las coordenadas siempre centra el mapa en el mar de Alborán.

Un saludo

**Comment by IngenieroGeomatico** [comment]
Buenas @e2molin 

La parametrización get de visualizadores está en esta página: https://github.com/IGN-CNIG/API-CNIG/wiki/6.-Parametrizaci%C3%B3n-Visualizadores


Actualmente tenemos los parámetros zoom, center, srs y layers.  ejemplo: https://www.ign.es/iberpix/visor/?zoom=14&srs=EPSG:4326&center=-7.1,38.68&layers=WMS*Limite*https://www.ign.es/wms-inspire/unidades-administrativas*AU.AdministrativeBoundary*true*false**1.3.0*true*true*true

En principio sustituyendo tu bbox por una coordenada central tendrías resuelto el problema

**Comment by e2molin** [comment]
Hola. Gracias por vuestra respuesta. 
Había extendido las parametrizaciones del APIREST a los visualizadores y pensaba que también funcionaban en ellos. En la página que me envías me queda más claro.
